/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    OrderCard: typeof import('./src/components/orders/OrderCard.vue')['default']
    OrdersCards: typeof import('./src/components/orders/OrdersCards.vue')['default']
    OrdersPagination: typeof import('./src/components/orders/OrdersPagination.vue')['default']
    OrdersSearchFilter: typeof import('./src/components/orders/OrdersSearchFilter.vue')['default']
    OrdersStatusFilter: typeof import('./src/components/orders/OrdersStatusFilter.vue')['default']
    OrdersTable: typeof import('./src/components/orders/OrdersTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusBadge: typeof import('./src/components/orders/StatusBadge.vue')['default']
    ViewMessage: typeof import('./src/components/ui/ViewMessage.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
